config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings'
    get "followers" => 'relationships#followers'
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index] do
    get 'search' => 'searches#tag_search'
  end

  get 'favorites' => 'favorites#index'
  get 'user_search' => 'searches#user_search'
  get 'post_search' => 'searches#post_search'

  get 'about' => 'homes#about'
  get 'timeline' => 'posts#timeline'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favarited_posts, through: :favorites, source: :post

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  attachment :icon

  # フォローメソッド
  def follow(other_user)
    relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  # ユーザー検索
  def self.looks(word)
    if word != ""
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@guest.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def guest_sign_in
    user = User.guest
    # ゲストユーザーをログイン状態にする
    sign_in user
    redirect_to user_path(user.id), notice: "ゲストユーザーでログインしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :ensure_correct_user, only: %i[edit update]
  before_action :ensure_guest_user, only: %i[edit update]

  def index
    @users = User.page(params[:page]).per(10)
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:icon, :name, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

  def ensure_guest_user
    user = User.find(params[:id])
    if user.name == 'guestuser'
      redirect_to user_path(current_user),
                  notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_index.html.erb
<div class = "container">
  <%= render "layouts/flash" %>

  <div id="profile">
    <div class="row mb-2 mx-auto" style="width:90%" >

      <div class="col-2">
        <%= attachment_image_tag @user, :icon, :fill, 110, 110, fallback: "no_image.png",size:"110x110",style:"border-radius:50%" %>
      </div>

      <div class="col-9 ml-auto">
        <div class="row m-0">
        <h4><%= @user.name %></h4>
        <div class="ml-auto">
          <% if user_signed_in? %>
            <% unless @user.id == current_user.id %>
              <% if current_user.following?(@user) %>
                <%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class:"btn btn-secondary " %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-outline-secondary" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        </div>

        <p><%= simple_format(@user.introduction) %></p>

        <div class="row text-center pt-3" style="width:90%">
          <p class="col-4"><%= @user.posts.count %>
            <br/>投稿
          </p>
          <p class="col-4"><%= link_to user_followings_path(@user.id) do %><%= @user.followings.count %>
            <br/>フォロー<%end%>
          </p>
          <p class="col-4"><%= link_to user_followers_path(@user.id) do %><%= @user.followers.count %>
            </br>フォロワー<%end%>
          </p>
        </div>

        <% if user_signed_in? && @user.id == current_user.id && @user.name != "guestuser" %>
            <p class="text-right"><%= link_to ">> edit profile", edit_user_path(@user) %></p>
        <% end %>

      </div>
    </div>
  </div>

  <div class="user-post">
    <%= render "posts/post_index", posts: @posts %>
  </div>

  <div class="my-5 ml-auto">
    <%= paginate(@posts) %>
  </div>

</div>

app/views/users/edit.html.erb
<div class = "container">
  <h2>EDIT PLOFILE</h2>
  <div class="row">
    <div class="col-md-6 mx-auto">

      <%= render "layouts/error", model: @user %>
      <%= form_with model: @user,url: user_path(current_user.id), local: true do |f| %>

        <div class="mt-5">
          <%= attachment_image_tag @user, :icon, :fill, 60, 60, fallback: "no_image.png",size:"60x60",style:"border-radius: 50%",class:"mb-2"%>
          <%= f.label :icon ,"アイコン"%><br />
          <%= f.file_field :icon %>
        </div>

        <div class="mt-4">
          <%= f.label :name ,"名前" %><br />
          <%= f.text_field :name, autofocus: true ,class:"form-control"%>
        </div>

        <div class="mt-4">
          <%= f.label :introduction, '紹介文' %><br />
          <%= f.text_area :introduction ,class:"form-control", rows: "5" %>
        </div>

        <div class="text-center mt-5">
          <%= f.submit 'update' ,class:"submit" %>
        </div>
        <div class="text-center mt-5">
          <%= link_to "back", user_path(@user) ,class:"back"%>
        </div>

      <%end%>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "container">

  <h2>USERS</h2>
  <%= render "searches/form_user_search" %>
  <%= render "user_index", users: @users %>

</div>

app/views/users/show.html.erb
<div class = "container">
  <%= render "layouts/flash" %>

  <div id="profile">
    <div class="row mb-2 mx-auto" style="width:90%" >

      <div class="col-2">
        <%= attachment_image_tag @user, :icon, :fill, 110, 110, fallback: "no_image.png",size:"110x110",style:"border-radius:50%" %>
      </div>

      <div class="col-9 ml-auto">
        <div class="row m-0">
        <h4><%= @user.name %></h4>
        <div class="ml-auto">
          <% if user_signed_in? %>
            <% unless @user.id == current_user.id %>
              <% if current_user.following?(@user) %>
                <%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class:"btn btn-secondary " %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-outline-secondary" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        </div>

        <p><%= simple_format(@user.introduction) %></p>

        <div class="row text-center pt-3" style="width:90%">
          <p class="col-4"><%= @user.posts.count %>
            <br/>投稿
          </p>
          <p class="col-4"><%= link_to user_followings_path(@user.id) do %><%= @user.followings.count %>
            <br/>フォロー<%end%>
          </p>
          <p class="col-4"><%= link_to user_followers_path(@user.id) do %><%= @user.followers.count %>
            </br>フォロワー<%end%>
          </p>
        </div>

        <% if user_signed_in? && @user.id == current_user.id && @user.name != "guestuser" %>
            <p class="text-right"><%= link_to ">> edit profile", edit_user_path(@user) %></p>
        <% end %>

      </div>
    </div>
  </div>

  <div class="user-post">
    <%= render "posts/post_index", posts: @posts %>
  </div>

  <div class="my-5 ml-auto">
    <%= paginate(@posts) %>
  </div>

</div>