config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings'
    get "followers" => 'relationships#followers'
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index] do
    get 'search' => 'searches#tag_search'
  end

  get 'favorites' => 'favorites#index'
  get 'user_search' => 'searches#user_search'
  get 'post_search' => 'searches#post_search'

  get 'about' => 'homes#about'
  get 'timeline' => 'posts#timeline'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def user_search
    # userモデルでlooks定義
    @users = User.looks(params[:word]).page(params[:page]).per(10)
    @word = params[:word]
  end

  def post_search
    @posts = Post.looks(params[:word]).page(params[:page]).per(10)
    @word = params[:word]
    @tags = Tag.all.sort { |a, b| b.posts.count <=> a.posts.count }
  end

  def tag_search
    @tags = Tag.all.sort { |a, b| b.posts.count <=> a.posts.count }
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.page(params[:page]).per(9)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form_post_search.html.erb
<%= form_with url: post_search_path, local: true, method: :get do |f| %>
    <div class="row mx-auto pt-3">
      <%= f.text_field :word , placeholder: "キーワード検索", class:"search form-control ml-auto" %>
      <%= button_tag type: 'submit' ,class: "btn mr-auto" do%>
        <i class="fas fa-search" style="color:#FFF;"></i>
      <%end%>
    </div>
<% end %>

app/views/searches/_form_tag_search.html.erb
<div class="tag-list">
  <p><i class="fas fa-tag"></i>タグで探す</p>
  <% tags.each do |tag| %>
    <% unless tag.posts.count == 0 %>
      <span class="pr-1">
        <%= link_to tag.name, tag_search_path(tag_id: tag.id) %><%="(#{tag.posts.count}) " %>
      </span>
    <%end%>
  <%end%>
</div>

app/views/searches/_form_user_search.html.erb
<div class="tag-list">
  <p><i class="fas fa-tag"></i>タグで探す</p>
  <% tags.each do |tag| %>
    <% unless tag.posts.count == 0 %>
      <span class="pr-1">
        <%= link_to tag.name, tag_search_path(tag_id: tag.id) %><%="(#{tag.posts.count}) " %>
      </span>
    <%end%>
  <%end%>
</div>

app/views/searches/post_search.html.erb
<div class = "container">

  <%= render "searches/form_tag_search", tags: @tags %>

  <h2>Search results '<%= @word %>'</h2>

  <div class="pt-3">
    <%= render "posts/post_index", posts: @posts %>
  </div>

  <div class="my-5 ml-auto">
    <%= paginate(@posts) %>
  </div>

</div>

app/views/searches/tag_search.html.erb
<div class = "container">

  <%= render "searches/form_tag_search", tags: @tags %>

  <h2><i class="fas fa-tag"></i><%= @tag.name %></h2>

  <%= render "posts/post_index", posts: @posts %>
  <div class="my-5 ml-auto">
    <%= paginate(@posts) %>
  </div>

</div>

app/views/searches/user_search.html.erb
<div class = "container">

  <h2>User '<%= @word %>'</h2>
  <%= render "searches/form_user_search" %>
  <%= render "users/user_index", users: @users %>

</div>