config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings'
    get "followers" => 'relationships#followers'
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index] do
    get 'search' => 'searches#tag_search'
  end

  get 'favorites' => 'favorites#index'
  get 'user_search' => 'searches#user_search'
  get 'post_search' => 'searches#post_search'

  get 'about' => 'homes#about'
  get 'timeline' => 'posts#timeline'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :entities, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships, source: :tag

  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  # 住所から緯度経度を取得
  geocoded_by :address
  after_validation :geocode

  validates :body, presence: true, length: { minimum: 2, maximum: 300 }

  # いいね確認メソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タグ保存・更新メソッド
  def save_tags(post_tag)
    # タグがあれば名前を全て取得
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - post_tag
    new_tags = post_tag - current_tags

    # 古いタグを削除
    old_tags.each do |old_tag|
      tags.delete Tag.find_by(name: old_tag)
    end

    # 新しいタグを追加
    new_tags.each do |new_tag|
      # 指定した値があれば取得、なければ作成する
      add_tag = Tag.find_or_create_by(name: new_tag)
      # 新しいタグを追加する
      tags << add_tag
    end
  end

  # キーワード（住所と投稿文）で検索
  def self.looks(word)
    if word != ''
      Post.where('body LIKE(?) OR address LIKE(?)', "%#{word}%", "%#{word}%")
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def new
    @post = Post.new
    @post.post_images.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    # 投稿ページからタグを取得、,で区切って配列にする
    tag_list = params[:post][:tag].split(',')
    if @post.save

      # APIでエンティティー取得
      entities = Language.get_data(post_params[:body])
      entities.each do |entity|
        @post.entities.create(name: entity)
      end

      # APIでタグ取得
      # 写真一枚ずつタグ取得
      @post.post_images.each do |post_image|
        # post.post_imageのimage_idカラムをvision.rbに渡す（post_imageモデルのattachmentがimageのため）
        api_tags = Vision.get_image_data(post_image.image)
        # tagを取り出して手入力したタグに追加　名前がカブらないようにする
        api_tags.each do |tag|
          tag_list << tag unless tag_list.include?(tag)
        end
      end
      @post.save_tags(tag_list)

      redirect_to post_path(@post), notice: '投稿しました'
    else
      render :new
    end
  end

  def index
    # いいね順が多いに並び替え
    posts = Post.includes(:favorited_users).sort { |a, b| b.favorited_users.size <=> a.favorited_users.size }
    # pagination使用
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(9)
    # タグは関連記事が多い順に表示
    @tags = Tag.all.sort { |a, b| b.posts.count <=> a.posts.count }
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
    post_comments = @post.post_comments.includes(:user).order('created_at DESC')
    # 新着の4件を表示
    @comments_latest = post_comments.first(4)
    # 4件を除くコメントを表示
    @comments_offset = post_comments.offset(4)
  end

  def edit
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    tag_list = params[:post][:tag].split(',')

    if @post.update(post_params)
      # 既存エンティティーの削除と新規作成
      @post.entities.destroy_all
      entities = Language.get_data(post_params[:body])
      entities.each do |entity|
        @post.entities.create(name: entity)
      end

      @post.post_images.each do |post_image|
        api_tags = Vision.get_image_data(post_image.image)
        api_tags.each do |tag|
          tag_list << tag unless tag_list.include?(tag)
        end
      end
      @post.save_tags(tag_list)

      redirect_to post_path(@post), notice: '投稿を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path(current_user), notice: '投稿を削除しました'
  end

  def timeline
    @users = current_user.followings
    posts = Post.where(user_id: @users).order('created_at DESC')
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(9)
  end

  private

  def post_params
    params.require(:post).permit(:body, :address, :atitude, :longitude, post_images_images: [])
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    redirect_to user_path(current_user) unless @post.user_id == current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_index.html.erb
<% unless posts.present? %>
  <p class="text-center font-weight-bold pt-5">Article not found</p>
<% else %>

  <div class="row pt-3">
    <% posts.each do |post| %>

      <div class="col-lg-4 col-sm-6 mt-3">
        <%=link_to post_path(post) do %>
            <% unless post.post_images.present? %>
              <div class="no-image" style="height: 230px;"></div>
            <%else%>
              <% post.post_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, class:"index-image" %>
              <%end%>
            <%end%>
        <% end %>

        <div class="row">
          <p class="col-10"><i class="fas fa-tag"></i><%= post.tags.take(3).map(&:name).join(', ') %></p>

          <% if user_signed_in? %>
            <p  id="post_<%= post.id %>" class="col-2 text-right">
              <%= render "favorites/iine", post: post %>
            </p>
          <%end%>
        </div>
      </div>

    <% end %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div class = "container">
  <h2>POST EDIT</h2>

  <div class="row">
    <div class="col-md-6 mx-auto">

      <%= render "layouts/error", model: @post %>
      <%= form_with model: @post, local: true do |f| %>

        <div class="mt-4">
          <%= f.label :post_images_images, "写真選択" %><br/>
          <%= f.file_field :post_images_images, multiple: true %>
        </div>

        <div class="mt-4">
          <%= f.label :address, '撮影場所' %>
          <%= f.text_field :address , placeholder:"住所、地名を入力してください" ,class:"form-control"%>
        </div>

        <div class="mt-4">
          <%= f.label :body ,"投稿文"%>
          <%= f.text_area :body, placeholder:"最大300字" ,class:"form-control", rows: "5" %>
        </div>

        <div class="mt-4">
                <%= f.label :tag ,"タグ"%>
          <%= f.text_field :tag, value: @tag_list, placeholder:"タグを複数つけるには' , 'で区切ってください" ,class:"form-control"%>
        </div>

        <div class="text-center mt-5">
          <%= f.submit 'update!' ,class:"submit"%>
        </div>

        <div class="text-center mt-5">
          <%= link_to "back", post_path(@post) ,class:"back"%>
        </div>

      <%end%>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">

  <%= render "searches/form_tag_search", tags: @tags %>

  <h2 class="top-line">ARTICLES</h2>

    <%= render "post_index", posts: @posts %>
    <div class="my-5 ml-auto">
      <%= paginate(@posts) %>
    </div>

 <%# 地図表示 %>
  <h2 class="top-line">MAP</h2>
<%# 検索フォーム %>
  <input id="address" type="textbox" value="大阪">
  <input type="button" value="検索" onclick="codeAddress()" class="btn btn-secondary btn-sm">
  <div id='index-map' style='width: 100%; height: 500px;' class="mt-3"></div>

</div>


<script>
  let map

  function initMap(){
    // geocoderを初期化
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('index-map'), {
        center: {lat: 35.68123620000001, lng:139.7671248},
        zoom: 7,
        styles:
              [
                  {
                      "featureType": "all",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "weight": "2.00"
                          }
                      ]
                  },
                  {
                      "featureType": "all",
                      "elementType": "geometry.stroke",
                      "stylers": [
                          {
                              "color": "#9c9c9c"
                          }
                      ]
                  },
                  {
                      "featureType": "all",
                      "elementType": "labels.text",
                      "stylers": [
                          {
                              "visibility": "on"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape",
                      "elementType": "all",
                      "stylers": [
                          {
                              "color": "#f2f2f2"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape.man_made",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "poi",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "all",
                      "stylers": [
                          {
                              "saturation": -100
                          },
                          {
                              "lightness": 45
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#eeeeee"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "color": "#7b7b7b"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.stroke",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "road.highway",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "simplified"
                          }
                      ]
                  },
                  {
                      "featureType": "road.arterial",
                      "elementType": "labels.icon",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "transit",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "all",
                      "stylers": [
                          {
                              "color": "#46bcec"
                          },
                          {
                              "visibility": "on"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#c8d7d4"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "color": "#070707"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels.text.stroke",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  }
              ]
    });


    <% @posts.each do |post| %>
        (function(){
        var contentString = "住所：<%= post.address %>";

        var marker = new google.maps.Marker({
            position:{lat: <%= post.atitude %>, lng: <%= post.longitude %>},
            map: map,
            title: contentString
        });

      })();
    <% end %>
    }

    let geocoder

    function codeAddress(){
      let inputAddress = document.getElementById('address').value;

      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

app/views/posts/new.html.erb
<div class = "container">

  <h2>NEW POST</h2>
  <div class="row">
    <div class="col-md-6 mx-auto">

      <%= render "layouts/error", model: @post %>
      <%= form_with model: @post, url: posts_path, method: :post, local: true do |f| %>

        <div class="mt-4">
          <%= f.label :post_images_images, "写真選択" %><br/>
          <%= f.file_field :post_images_images, multiple: true %>
        </div>

        <div class="mt-4">
          <%= f.label :address, '撮影場所' %>
          <%= f.text_field :address, placeholder:"住所、地名を入力してください", class:"form-control"%>
        </div>

        <div class="mt-4">
          <%= f.label :body ,"投稿文"%>
          <%= f.text_area :body, placeholder:"最大300字" ,class:"form-control", rows: "5" %>
        </div>

        <div class="mt-4">
          <%= f.label :tag ,"タグ"%>
          <%= f.text_field :tag, placeholder:"タグを複数つけるには' , 'で区切ってください" ,class:"form-control"%>
        </div>

        <div class="text-center mt-5">
          <%= f.submit 'post!' ,class:"submit"%>
        </div>
        <div class="text-center mt-5">
          <%= link_to "back", posts_path ,class:"back"%>
        </div>

      <%end%>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%= render "layouts/flash" %>

  <div class="row mt-3" style="height: 600px;">
    <% unless @post.post_images.present? %>
      <div class="no-image"  style="height: 600px;">
        <span>No image is available</span>
      </div>
    <%else%>
      <div id="show-images">
        <% @post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image ,class:"img-fluid"%>
        <% end %>
      </div>
    <%end%>
  </div>

  <% if user_signed_in? %>
    <div id="post_<%= @post.id %>" class="text-right">
      <%= render "favorites/iine", post: @post %>
    </div>
  <% end %>

  <div class="row my-5">
    <div id="post-user-card" class="col-md-6 mb-5">

      <div class="bottom-line pl-3">
        <%= link_to user_path(@user) ,class:"row" do %>
          <%= attachment_image_tag @user, :icon, :fill, 60, 60, fallback: "no_image.png",size:"60x60",style:"border-radius:50%" %>
          <h5 class="pt-3 pl-3"><%= @user.name %></h5>
        <% end %>
      </div>

      <p class="pt-3">撮影場所：<%= @post.address %></p>
      <p class="pt-3"><%= safe_join(@post.body.split("\n"),tag(:br)) %></p>
      <p id="post-tag" class="pt-3">
        <% @post.tags.each do |tag| %>
          <%= link_to tag_search_path(tag_id: tag.id) do %>
            <p><i class="fas fa-tag"></i><%=tag.name%><%="(#{tag.posts.count})" %></p>
          <%end%>
        <%end%>
      </p>
      <p class="pt-5">エンティティー分析
        <p>
          <% @post.entities.each do |entity| %><span><%= entity.name %><span><%end%>
        </p>
      </p>
      <% if user_signed_in? && @user.id == current_user.id %>
        <div class="text-right">
          <%= link_to "edit.  ", edit_post_path(@post) ,style:"color:#9e665d;"%><br/>
          <%= link_to "delete.", post_path(@post), method: :delete, data: {confirm: "本当に削除しますか？"} ,style:"color:#9e665d;"%>
        </div>
      <% end %>
    </div>

    <div class="col-md-5 offset-md-1">
      <div id="map" style='width: 100%; height: 400px;'></div>
    </div>

  </div>

  <h2 class="top-line">COMMENT</h2>

  <div class="row pt-3">
    <div class="col-md-4">
      <%= form_with(model:[@post, @post_comment], remote: true) do |f| %>
        <%= f.text_area :comment, rows:'5',placeholder: "コメント入力" ,class:"form-control"%>
        <%= f.submit "送信する" ,class:"btn btn-outline-secondary mt-1 mb-5"%>
      <% end %>
      <% unless user_signed_in? %>
        <p>※コメントを送るには<%= link_to "ログイン", new_user_session_path ,style:"color: #9e665d;"%>が必要です</p>
      <%end%>
    </div>

    <div class="col-md-7 offset-md-1">
      <div id="first_comment_area">
        <%= render "post_comments/comment", post_comments: @comments_latest %>
      </div>
      <!--5件目以降を表示-->
      <details>
        <summary>全てのコメントを表示</summary>

        <div id="last_comment_area">
          <%= render "post_comments/comment", post_comments: @comments_offset %>
        </div>
      </details>
    </div>
  </div>

</div>

<!--map表示-->
<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @post.atitude %>, lng: <%= @post.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: test,
            styles:
              [
                  {
                      "featureType": "all",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "weight": "2.00"
                          }
                      ]
                  },
                  {
                      "featureType": "all",
                      "elementType": "geometry.stroke",
                      "stylers": [
                          {
                              "color": "#9c9c9c"
                          }
                      ]
                  },
                  {
                      "featureType": "all",
                      "elementType": "labels.text",
                      "stylers": [
                          {
                              "visibility": "on"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape",
                      "elementType": "all",
                      "stylers": [
                          {
                              "color": "#f2f2f2"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "landscape.man_made",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "poi",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "all",
                      "stylers": [
                          {
                              "saturation": -100
                          },
                          {
                              "lightness": 45
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#eeeeee"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "color": "#7b7b7b"
                          }
                      ]
                  },
                  {
                      "featureType": "road",
                      "elementType": "labels.text.stroke",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  },
                  {
                      "featureType": "road.highway",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "simplified"
                          }
                      ]
                  },
                  {
                      "featureType": "road.arterial",
                      "elementType": "labels.icon",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "transit",
                      "elementType": "all",
                      "stylers": [
                          {
                              "visibility": "off"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "all",
                      "stylers": [
                          {
                              "color": "#46bcec"
                          },
                          {
                              "visibility": "on"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "geometry.fill",
                      "stylers": [
                          {
                              "color": "#c8d7d4"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels.text.fill",
                      "stylers": [
                          {
                              "color": "#070707"
                          }
                      ]
                  },
                  {
                      "featureType": "water",
                      "elementType": "labels.text.stroke",
                      "stylers": [
                          {
                              "color": "#ffffff"
                          }
                      ]
                  }
              ]
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @post.address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });


    }  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

app/views/posts/timeline.html.erb
<div class = "container">

  <h2>TIMELINE</h2>

  <%= render "post_index", posts: @posts %>
  <div class="my-5 ml-auto">
    <%= paginate(@posts) %>
  </div>

</div>