config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings'
    get "followers" => 'relationships#followers'
  end

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index] do
    get 'search' => 'searches#tag_search'
  end

  get 'favorites' => 'favorites#index'
  get 'user_search' => 'searches#user_search'
  get 'post_search' => 'searches#post_search'

  get 'about' => 'homes#about'
  get 'timeline' => 'posts#timeline'
end

app/views/layouts/_error.html.erb
<div class="mb-3">
  <% if model.errors.any? %>
    <%= model.errors.count %>件のエラーが発生しました
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="text-success"><%= notice %></p>
  <% elsif alert %>
  <p class="text-danger"><%= alert %></p>
<%end%>

app/views/layouts/_footer.html.erb
<footer>
  <p>© 2021 machinaka.</p>
</footer>

app/views/layouts/_header.html.erb
<!--fixed-top でヘッダー固定　sticky-topで固定なし-->
<header class="fixed-top">
  <div class="brand">
    <%= link_to "Machinaka Light" ,root_path %>
  </div>
  <div class="social">
    <% if user_signed_in? %>
      <%= link_to user_path(current_user) do%><i class="far fa-user fa-lg"></i><%end%>
    <% else %>
      <%= link_to new_user_session_path do%><i class="far fa-user fa-lg"></i><%end%>
    <% end %>
    <%= link_to favorites_path do%><i class="far fa-heart fa-lg"></i><%end%>
  </div>

  <div id="sp-menu">
    <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to root_path do %><span>top</span><%end%>
        </li>
        <li>
          <%= link_to timeline_path do %><span>timeline</span><%end%>
        </li>
        <li>
          <%= link_to favorites_path do %><span>favorites</span><%end%>
        </li>
        <li>
          <%= link_to new_post_path do %><span>new post</span><%end%>
        </li>
        <li>
          <%= link_to posts_path do %><span>articles</span><%end%>
        </li>
        <li>
          <%= link_to users_path do %><span>users</span><%end%>
        </li>
        <li>
          <%= link_to user_path(current_user.id) do %><span>mypage</span><%end%>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %><span>logout</span><%end%>
        </li>
      <% else %>
        <li>
          <%= link_to root_path do %><span>top</span><%end%>
        </li>
        <li>
          <%= link_to about_path do %><span>about</span><%end%>
        </li>
        <li>
          <%= link_to posts_path do %><span>articles</span><%end%>
        </li>
        <li>
          <%= link_to users_path do %><span>users</span><%end%>
        </li>
        <li>
          <%= link_to new_user_session_path do %><span>login</span><%end%>
        </li>
        <li>
          <%= link_to new_user_registration_path do %><span>signup</span><%end%>
        </li>
      <% end %>
      <%= render "searches/form_post_search" %>
    </ul>
  </div>

  <div id="hm-icon">
    <a class="menu-trigger" href="#">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfMachinaka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--フォント変更-->
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Estonia&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">

  <body>
    <%= render "layouts/header" %>
    <%= yield %>

    <span id="arrow">
      <a href="#">
        <%= image_tag asset_path("arrow2.png"), class:"arrow-img" %>
      </a>
    </span>

    <%= render "layouts/footer" %>

  </body>
</html>